#!/bin/bash

# Update system
sudo apt update -y && sudo apt upgrade -y

# Install Java 8 (OpenJDK 8)
sudo apt install openjdk-8-jdk unzip wget -y

# Verify Java
java -version

# Download JFrog Artifactory OSS
wget https://releases.jfrog.io/artifactory/artifactory-oss/org/artifactory/oss/jfrog-artifactory-oss/6.9.6/jfrog-artifactory-oss-6.9.6.zip

# Unzip it
unzip jfrog-artifactory-oss-6.9.6.zip

# Start Artifactory
cd jfrog-artifactory-oss-6.9.6
bash bin/artifactory.sh start


#Port Number: 8081
